### ISSUE TITLE
 System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

### ISSUE THREAD

**Issue by TonyHenrique** [GrillPhil/ServerlessRealtimeDemo#1]
I used the code from on my UWP Application

But when I run it, 

```
On the SignalRService class, method Init()
on this line
new HubConnectionBuilder().WithUrl(info.Endpoint, (options) => options.AccessTokenProvider = () => Task.FromResult<string>(info.AccessKey))
```

throws 

> System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. O sistema não pode encontrar o arquivo especificado.'

I did not find a NuGet that matches this version 4.0.1.0

![sm](https://user-images.githubusercontent.com/6307623/40571604-354a3412-6072-11e8-85d6-11d8ac7c97bc.png)

My UWP Project is 
Target version: 
Windows 10, version 1803 (10.0; Build 17134)

Min version:
Windows 10, version 1803 (10.0; Build 17134)
![ss](https://user-images.githubusercontent.com/6307623/40571629-c3104dc2-6072-11e8-9a53-38fed9df894b.png)

![ss1](https://user-images.githubusercontent.com/6307623/40571642-1f3a9094-6073-11e8-95b0-c6047481a6c6.png)

**Comment by TonyHenrique** [comment]
Someone else is also having this issue with the Microsoft.AspNetCore.SignalR.Client
https://github.com/aspnet/SignalR/issues/1294#issuecomment-390896218

**Comment by TonyHenrique** [comment]
Is this System.Memory issue related to this? https://github.com/SixLabors/ImageSharp/issues/459#issuecomment-364038108

**Comment by TonyHenrique** [comment]
If I set
Target version: 
Windows 10, version 1803 (10.0; Build 17134)

Min version:
Windows 10 Fall Creators Update (10.0; Build 16299)

Then it works.

![works](https://user-images.githubusercontent.com/6307623/40577542-d9fd7c06-60dd-11e8-903e-bd1784a89ab4.png)

**Comment by GrillPhil** [comment]
So this is what I recommended in the first place ;-) seems to be an issue within UWP 1803 so I will close this for now.
